# Generated by Django 5.1 on 2024-09-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoenix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('whatsapp_number', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
