# Generated by Django 5.1 on 2024-09-04 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phoenix', '0004_avis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avis',
            name='produit',
        ),
    ]
